name: deploy-book

# Only run this when the master branch's book folder changes
on:
  push:
    paths:
    - book/**
    branches:
    - master

# This job installs dependencies, build the book, and pushes it to `gh-pages`
jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
    - name: Git clone and checkout master
      uses: actions/checkout@v2

    # Install dependencies
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Install book dependencies
      run: |
        pip install -r book/requirements.txt

    # Build the book
    - name: Build the book
      run: |
        jupyter-book build ./book

    # Push the book's HTML to github-pages
    - name: Push built book to gh-pages branch
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./book/_build/html
        publish_branch: gh-pages
